# Data Transformation in Pandas

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [4]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [5]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [6]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [7]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [8]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [9]:
n=df["names"].str.capitalize()

In [10]:
df["branches"]=n.map(classes)

In [11]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [12]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [13]:
import numpy as np

In [14]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [15]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [16]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [17]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [18]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [19]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [20]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [21]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [22]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [23]:
x=[20,40,60,80,100]

In [24]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [25]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [26]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [27]:
pd.value_counts(y)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [28]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [29]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [30]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [31]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(-3.3489999999999998, -0.761], (-3.3489999999999998, -0.761], (0.718, 2.417], (-0.761, -0.0781], (-0.761, -0.0781], ..., (0.718, 2.417], (-0.0781, 0.718], (-0.0781, 0.718], (-0.761, -0.0781], (-0.761, -0.0781]]
Length: 100
Categories (4, interval[float64, right]): [(-3.3489999999999998, -0.761] < (-0.761, -0.0781] < (-0.0781, 0.718] < (0.718, 2.417]]

In [32]:
pd.value_counts(c)

(-3.3489999999999998, -0.761]    25
(-0.761, -0.0781]                25
(-0.0781, 0.718]                 25
(0.718, 2.417]                   25
dtype: int64

In [33]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0 -0.258361 -0.824145  0.089965 -1.140243
1  0.653484  0.921507  0.056745  0.593330
2 -0.482052  1.686051 -0.855666 -1.538701
3  0.553903 -0.457784 -1.453866 -0.999566
4  1.117788  2.665641 -0.932829 -0.340817

In [34]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.033317     0.038511     0.017668    -0.038245
std       0.973812     1.009606     1.018078     1.017050
min      -3.505708    -3.260415    -3.102506    -2.980412
25%      -0.690583    -0.606902    -0.643017    -0.721999
50%      -0.002132     0.026031     0.002826    -0.028859
75%       0.628809     0.650334     0.699381     0.628738
max       2.791287     3.547068     3.267972     3.238727

In [35]:
col=data[1]

In [36]:
col[np.abs(col)>3]

29     3.008226
169    3.002193
586    3.547068
640   -3.178093
762   -3.050935
834   -3.260415
Name: 1, dtype: float64

In [37]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
29   0.759830  3.008226  1.468934 -0.701398
128  0.649755  0.747568  1.071750  3.238727
151 -1.543159  0.110357 -3.022304  0.388959
155 -0.171338  0.338855 -3.102506 -0.003804
169  0.097052  3.002193  0.405163 -1.130348
223  1.280745  0.149249  3.267972  0.168097
439 -3.360334  1.117923  0.968666  0.855864
478 -3.153801  0.390479  1.589838  1.090939
586 -0.051738  3.547068  0.438588  1.692087
640  0.414697 -3.178093 -2.034190 -2.181267
762 -0.089523 -3.050935 -0.715987  1.065352
791 -3.505708 -0.387743  0.661745 -1.620638
834 -0.154351 -3.260415 -0.452813  0.866244
961  0.161239 -0.029584 -0.243410  3.031280

In [38]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1  1.0  1.0  1.0  1.0
2 -1.0  1.0 -1.0 -1.0
3  1.0 -1.0 -1.0 -1.0
4  1.0  1.0 -1.0 -1.0

In [39]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [40]:
rw=np.random.permutation(4)
rw

array([3, 0, 1, 2])

In [41]:
data.take(rw)

0   1   2
3  9  10  11
0  0   1   2
1  3   4   5
2  6   7   8

In [42]:
data.sample()

0  1  2
2  6  7  8

In [43]:
data.sample(n=2)

0   1   2
3  9  10  11
1  3   4   5

## Dummy Variable

In [44]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [45]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [46]:
data=np.random.randn(10)
data

array([-0.11267364, -1.64279231,  0.24900589,  0.58433039,  1.48140296,
        0.96369998,  0.58857622, -1.0997079 , -1.07366009,  0.41602224])

In [47]:
pd.get_dummies(pd.cut(data,4))

(-1.646, -0.862]  (-0.862, -0.0807]  (-0.0807, 0.7]  (0.7, 1.481]
0                 0                  1               0             0
1                 1                  0               0             0
2                 0                  0               1             0
3                 0                  0               1             0
4                 0                  0               0             1
5                 0                  0               0             1
6                 0                  0               1             0
7                 1                  0               0             0
8                 1                  0               0             0
9                 0                  0               1             0